# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-14 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artlic',
            new_name='Artic',
        ),
        migrations.AlterModelTable(
            name='artic',
            table='artic',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publish',
        ),
    ]
