# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oto.Author'),
        ),
    ]
