# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200114_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=254, verbose_name='邮箱'),
        ),
    ]
